export const GET_PRODUCTS = 'GET_PRODUCTS';
export const GET_PRODUCT_REVIEWS = 'GET_PRODUCT_REVIEWS';
export const POST_PRODUCT_REVIEW = 'POST_PRODUCT_REVIEW';
export const UPDATE_PRODUCT_REVIEW = 'UPDATE_PRODUCT_REVIEW';
export const GET_PRODUCT_DETAILS = 'GET_PRODUCT_DETAILS';
export const GET_ABOUTUS_DETAILS = 'GET_ABOUTUS_DETAILS';
export const GET_CONTACTUS_DETAILS = 'GET_CONTACTUS_DETAILS';
export const POST_GETINTOUCH_DETAILS = 'POST_GETINTOUCH_DETAILS';